import fs from 'fs'
import path from 'path'
import chalk from 'chalk'
import ora from 'ora'

interface RepoGraph {
  repoName: string
  repoPath: string
  systemName: string
  services: Array<{ canonical: string; file: string; aliases: string[]; dependents: number; classification: string }>
  nodes: Array<{ id: string; label: string; layer: string }>
  edges: Array<{ from: string; to: string; label: string }>
}

interface CrossRepoEdge {
  fromRepo: string
  fromService: string
  toRepo: string
  toService: string
  matchedBy: string   // which alias triggered the match
}

function loadRepoGraph(repoPath: string): RepoGraph | null {
  const graphPath = path.join(repoPath, 'legibly', 'graph.json')
  try {
    const raw = JSON.parse(fs.readFileSync(graphPath, 'utf-8'))
    return {
      repoName: path.basename(repoPath),
      repoPath,
      systemName: raw.systemName ?? path.basename(repoPath),
      services: raw.services ?? [],
      nodes: raw.nodes ?? [],
      edges: raw.edges ?? [],
    }
  } catch { return null }
}

function findRepos(workspace: string): string[] {
  try {
    return fs.readdirSync(workspace, { withFileTypes: true })
      .filter((e) => e.isDirectory())
      .map((e) => path.join(workspace, e.name))
      .filter((p) => fs.existsSync(path.join(p, 'legibly', 'graph.json')))
  } catch { return [] }
}

function buildCrossRepoEdges(graphs: RepoGraph[]): CrossRepoEdge[] {
  const edges: CrossRepoEdge[] = []

  // Build a lookup: all known names → { repo, canonical }
  const nameIndex = new Map<string, { repo: string; canonical: string }>()
  for (const g of graphs) {
    for (const svc of g.services) {
      const register = (name: string): void => {
        if (name) nameIndex.set(name.toLowerCase(), { repo: g.repoName, canonical: svc.canonical })
      }
      register(svc.canonical)
      register(svc.file)
      for (const alias of svc.aliases) register(alias)
    }
  }

  // For each repo's services, check if any alias resolves to a different repo
  for (const g of graphs) {
    for (const svc of g.services) {
      const allNames = [svc.canonical, svc.file, ...svc.aliases]
      for (const name of allNames) {
        const match = nameIndex.get(name.toLowerCase())
        if (match && match.repo !== g.repoName) {
          edges.push({
            fromRepo: g.repoName,
            fromService: svc.canonical,
            toRepo: match.repo,
            toService: match.canonical,
            matchedBy: name,
          })
        }
      }
    }
  }

  // Deduplicate
  const seen = new Set<string>()
  return edges.filter((e) => {
    const key = `${e.fromRepo}:${e.fromService}→${e.toRepo}:${e.toService}`
    if (seen.has(key)) return false
    seen.add(key)
    return true
  })
}

function renderPlatformMap(graphs: RepoGraph[], crossEdges: CrossRepoEdge[]): string {
  const date = new Date().toISOString().slice(0, 10)

  const repoRows = graphs.map((g) =>
    `| ${g.repoName} | ${g.systemName} | ${g.services.length} |`
  ).join('\n')

  const crossRows = crossEdges.length > 0
    ? crossEdges.map((e) =>
        `| ${e.fromRepo} / ${e.fromService} | → | ${e.toRepo} / ${e.toService} | via \`${e.matchedBy}\` |`
      ).join('\n')
    : '_No cross-repo dependencies detected._'

  // Build repos-touched across repos
  const repoDeps = new Map<string, Set<string>>()
  for (const e of crossEdges) {
    if (!repoDeps.has(e.toRepo)) repoDeps.set(e.toRepo, new Set())
    repoDeps.get(e.toRepo)!.add(e.fromRepo)
  }

  const touchedRows = [...repoDeps.entries()]
    .sort(([, a], [, b]) => b.size - a.size)
    .map(([repo, dependents]) =>
      `| **${repo}** | ${[...dependents].join(', ')} | Changes here affect ${dependents.size} other repo${dependents.size !== 1 ? 's' : ''} |`
    ).join('\n')

  return `# Platform Map

> Generated by [Legibly](https://github.com/prayasjain/legibly) on ${date}
> Synthesised from ${graphs.length} repo${graphs.length !== 1 ? 's' : ''}

## Repos

| Repo | System | Services |
|------|--------|---------|
${repoRows}

## Cross-repo dependencies

| From | | To | Matched by |
|------|---|-----|-----------|
${crossRows}

## Repos-touched (cross-repo blast radius)

| If you change... | Check these repos | Why |
|-----------------|-------------------|-----|
${touchedRows || '_No cross-repo blast radius detected._'}

---

*Re-generate with \`legibly platform\` from the workspace root.*
`
}

export async function runPlatform(
  workspace: string,
  opts: { output?: string } = {}
): Promise<void> {
  const spinner = ora('Scanning workspace for legibly output...').start()

  const repoPaths = findRepos(workspace)
  if (repoPaths.length === 0) {
    spinner.fail('No repos with legibly output found. Run `legibly analyse` in each repo first.')
    return
  }

  spinner.text = `Loading ${repoPaths.length} repo graphs...`
  const graphs = repoPaths.map(loadRepoGraph).filter((g): g is RepoGraph => g !== null)
  spinner.succeed(chalk.dim(`Loaded ${graphs.length} repos: ${graphs.map((g) => g.repoName).join(', ')}`))

  spinner.start('Computing cross-repo dependencies...')
  const crossEdges = buildCrossRepoEdges(graphs)
  spinner.succeed(chalk.dim(`Found ${crossEdges.length} cross-repo connection${crossEdges.length !== 1 ? 's' : ''}`))

  spinner.start('Writing platform map...')
  const outputDir = opts.output ?? workspace
  fs.mkdirSync(outputDir, { recursive: true })

  const mapPath = path.join(outputDir, 'PLATFORM_MAP.md')
  fs.writeFileSync(mapPath, renderPlatformMap(graphs, crossEdges), 'utf-8')

  const graphPath = path.join(outputDir, 'platform-graph.json')
  fs.writeFileSync(graphPath, JSON.stringify({ repos: graphs.map((g) => ({ name: g.repoName, systemName: g.systemName, services: g.services.length })), crossEdges }, null, 2), 'utf-8')

  spinner.succeed(chalk.dim(`Platform map written`))

  console.log(chalk.bold('\n✓ Platform synthesis complete\n'))
  console.log(`  ${chalk.white(mapPath)}`)
  console.log(`  ${chalk.white(graphPath)}`)
  if (crossEdges.length > 0) {
    console.log(chalk.yellow(`\n  ${crossEdges.length} cross-repo connection${crossEdges.length !== 1 ? 's' : ''} found`))
  } else {
    console.log(chalk.dim('\n  No cross-repo connections found — services may have different names across repos.'))
    console.log(chalk.dim('  Tip: Use consistent service names or add aliases in each repo\'s legibly output.'))
  }
  console.log()
}
