import type { SystemAnalysis } from '../stitcher/types.js'

export function renderAliasResolution(system: SystemAnalysis): string {
  const aliases = system.aliases

  const tableRows = aliases
    .sort((a, b) => b.dependents - a.dependents)
    .map((a) => {
      const aliasCell = a.aliases.length > 0 ? a.aliases.join(', ') : '—'
      const badge = a.classification === 'core' ? ' ⬤' : ''
      return `| ${a.canonical}${badge} | \`${a.file}\` | ${aliasCell} | ${a.dependents} |`
    })
    .join('\n')

  const coreCount = aliases.filter((a) => a.classification === 'core').length

  return `# Alias Resolution Table

> Generated by [Legibly](https://github.com/prayasjain/legibly) on ${new Date().toISOString().slice(0, 10)}

Use this table to resolve any service name you encounter — in env vars, logs, code comments, or PR descriptions — to its canonical name and entry point file.

**⬤ = core service** (3+ dependents — highest blast radius)

| Canonical Name | File | Also known as | Dependents |
|----------------|------|---------------|-----------|
${tableRows || '_No services detected._'}

## Quick resolution guide

When you see a name you don't recognise, scan the **"Also known as"** column. If it's listed there, the row's **Canonical Name** is what the code actually calls it.

${coreCount > 0 ? `## Core services (${coreCount})

These are the most-depended-upon services. Treat changes here with extra care — they affect the most downstream code.

${aliases.filter((a) => a.classification === 'core').map((a) =>
  `- **${a.canonical}** — \`${a.file}\` — ${a.dependents} dependents${a.aliases.length > 0 ? ` (${a.aliases.join(', ')})` : ''}`
).join('\n')}` : ''}

---

*Aliases are detected from import statements and \`usedBy\` relationships. Re-generate with \`legibly analyse --stitch-only\`.*
`
}
