import type { Assessment } from '../assessor/types.js'

const SCORE_BAR_WIDTH = 20

function scoreBar(score: number, max = 4): string {
  const filled = Math.round((score / max) * SCORE_BAR_WIDTH)
  return '█'.repeat(filled) + '░'.repeat(SCORE_BAR_WIDTH - filled)
}

function levelEmoji(name: string): string {
  const map: Record<string, string> = {
    'Manual':     '⚙️',
    'Assisted':   '💡',
    'Paired':     '🤝',
    'Trusted':    '🎯',
    'Autonomous': '🤖',
  }
  return map[name] ?? '•'
}

export function renderAssessment(assessment: Assessment): string {
  const { overallScore, level, nextLevel, dimensions, toNextLevel } = assessment
  // assessment is also used directly below for hardBlockers/safeForAI/requiresReview/avoidAI

  const levelTable = [
    { number: 1, name: 'Manual',     range: '0.0–1.0',  meaning: 'Human writes everything; AI can only explain' },
    { number: 2, name: 'Assisted',   range: '1.1–2.0',  meaning: 'AI suggests; human reviews every change' },
    { number: 3, name: 'Paired',     range: '2.1–2.8',  meaning: 'AI writes and applies; human reviews before commit' },
    { number: 4, name: 'Trusted',    range: '2.9–3.5',  meaning: 'AI writes, tests, commits; human reviews PRs' },
    { number: 5, name: 'Autonomous', range: '3.6–4.0',  meaning: 'AI operates end-to-end; human monitors outcomes' },
  ].map((l) => {
    const current = l.name === level.name ? ' ← **YOU ARE HERE**' : ''
    return `| ${levelEmoji(l.name)} ${l.name} | ${l.range} | ${l.meaning}${current} |`
  }).join('\n')

  const dimensionRows = dimensions.map((d) => {
    const bar = scoreBar(d.score)
    return `| ${d.name} | ${d.score.toFixed(1)} | \`${bar}\` |`
  }).join('\n')

  const dimensionDetails = dimensions.map((d) => {
    const signals = d.signals.map((s) => `  - ✓ ${s}`).join('\n')
    const gaps = d.gaps.map((g) => `  - ✗ ${g}`).join('\n')
    return `### ${d.name} — ${d.score.toFixed(1)} / 4.0\n\n${signals || '  - (no positive signals)'}\n${gaps || ''}`
  }).join('\n\n')

  const nextLevelSection = nextLevel
    ? `## What would unlock ${levelEmoji(nextLevel.name)} ${nextLevel.name}\n\n${toNextLevel.map((a) => `- ${a}`).join('\n')}`
    : `## Maximum autonomy reached 🤖\n\nThis codebase has the safety nets in place for AI to operate end-to-end. The work now is maintaining that standard — don't let coverage, security, or documentation drift.`

  const blockersSection = assessment.hardBlockers.length > 0
    ? `## Hard blockers\n\nThese conditions cap the maximum safe AI autonomy level regardless of overall score:\n\n${assessment.hardBlockers.map((b) => `- ⛔ ${b}`).join('\n')}`
    : `## Hard blockers\n\nNone — no conditions that force a level cap.`

  const safeZonesSection = `## Safe zones for AI at this level

**Safer for AI autonomy:**
${assessment.safeForAI.length > 0 ? assessment.safeForAI.map((s) => `- ✓ ${s}`).join('\n') : '- None identified at this level'}

**Requires human review before merge:**
${assessment.requiresReview.length > 0 ? assessment.requiresReview.map((r) => `- ⚠ ${r}`).join('\n') : '- No specific concerns'}

**Avoid delegating to AI without discussion:**
${assessment.avoidAI.length > 0 ? assessment.avoidAI.map((a) => `- ✗ ${a}`).join('\n') : '- None'}`

  return `# AI Readiness Score

> Generated by [Legibly](https://github.com/prayasjain/legibly) on ${new Date().toISOString().slice(0, 10)}
>
> How autonomously can AI operate in this codebase — right now, safely, without a human checking everything?

## Current level

# ${levelEmoji(level.name)} Level ${level.number}: ${level.name}

**Score: ${overallScore.toFixed(2)} / 4.00**

\`${scoreBar(overallScore)}\`

> ${level.meaning}

## The autonomy scale

| Level | Score | What it means |
|-------|-------|---------------|
${levelTable}

## Score by dimension

| Dimension | Score | Progress |
|-----------|-------|----------|
${dimensionRows}

## Dimension breakdown

${dimensionDetails}

${blockersSection}

${safeZonesSection}

${nextLevelSection}

---

*Run \`legibly analyse\` to generate the full context bundle, or \`legibly assess\` to refresh this score.*
`
}
