import type { SystemAnalysis } from '../stitcher/types.js'
import type { ChunkAnalysis } from '../analyser/types.js'

interface TouchEntry {
  /** The module being changed */
  subject: string
  subjectFile: string
  /** Modules that also need attention when subject changes */
  alsoTouch: Array<{ name: string; file: string; why: string }>
}

/**
 * Build a "repos-touched" lookup from two sources:
 * 1. Each chunk's `usedBy` list — direct "A is used by B" relationships
 * 2. The dependency graph edges — "A depends on B" → changing B, check A
 */
function buildTouchMap(system: SystemAnalysis): TouchEntry[] {
  const chunks = system.chunkAnalyses

  // Index chunks by their entry-point file for fast lookup
  const chunkByFile = new Map<string, ChunkAnalysis>()
  const chunkByName = new Map<string, ChunkAnalysis>()
  for (const c of chunks) {
    chunkByFile.set(c.file, c)
    chunkByName.set(c.name, c)
  }

  // Build inverse dependency map: file → list of modules that depend on it
  // Source 1: chunk.usedBy fields
  const usedByMap = new Map<string, Array<{ name: string; file: string; why: string }>>()

  for (const chunk of chunks) {
    for (const usage of chunk.usedBy) {
      // usage.file is the consumer; chunk is the thing being used
      const consumerChunk = chunkByFile.get(usage.file)
      const consumerName = consumerChunk?.name ?? usage.file
      const consumerFile = usage.file

      if (!usedByMap.has(chunk.file)) usedByMap.set(chunk.file, [])
      usedByMap.get(chunk.file)!.push({
        name: consumerName,
        file: consumerFile,
        why: usage.context || `used by ${consumerName}`,
      })
    }
  }

  // Source 2: dependency graph edges — edge (from → to) means "from depends on to"
  // So changing "to" → you need to check "from"
  for (const edge of system.dependencyGraph.edges) {
    const dependentNode = system.dependencyGraph.nodes.find((n) => n.id === edge.from)
    const dependencyNode = system.dependencyGraph.nodes.find((n) => n.id === edge.to)
    if (!dependentNode || !dependencyNode) continue

    const dependentChunk = chunkByName.get(dependentNode.label) ?? chunkByFile.get(edge.from)
    const dependencyChunk = chunkByName.get(dependencyNode.label) ?? chunkByFile.get(edge.to)
    if (!dependentChunk || !dependencyChunk) continue

    // Avoid duplicates already captured via usedBy
    const existing = usedByMap.get(dependencyChunk.file) ?? []
    const alreadyPresent = existing.some((e) => e.file === dependentChunk.file)
    if (!alreadyPresent) {
      if (!usedByMap.has(dependencyChunk.file)) usedByMap.set(dependencyChunk.file, [])
      usedByMap.get(dependencyChunk.file)!.push({
        name: dependentChunk.name,
        file: dependentChunk.file,
        why: `${edge.label ?? 'depends on'} this module`,
      })
    }
  }

  // Build the final list — only modules that have at least one dependent
  const entries: TouchEntry[] = []
  for (const chunk of chunks) {
    const dependents = usedByMap.get(chunk.file)
    if (!dependents || dependents.length === 0) continue

    // Deduplicate by file
    const seen = new Set<string>()
    const unique = dependents.filter((d) => {
      if (seen.has(d.file)) return false
      seen.add(d.file)
      return true
    })

    entries.push({
      subject: chunk.name,
      subjectFile: chunk.file,
      alsoTouch: unique,
    })
  }

  // Sort: most dependents first (highest blast radius at top)
  entries.sort((a, b) => b.alsoTouch.length - a.alsoTouch.length)
  return entries
}

export function renderBlastRadius(system: SystemAnalysis): string {
  const entries = buildTouchMap(system)

  if (entries.length === 0) {
    return `# Repos-Touched Quick Lookup

> Generated by [Legibly](https://github.com/prayasjain/legibly) on ${new Date().toISOString().slice(0, 10)}

No cross-module dependencies detected.
`
  }

  const tableRows = entries.flatMap((entry) =>
    entry.alsoTouch.map((dep, i) => {
      const subject = i === 0 ? `**${entry.subject}**` : ''
      return `| ${subject} | ${dep.name} | ${dep.why} |`
    })
  ).join('\n')

  const detailSections = entries.map((entry) => {
    const deps = entry.alsoTouch
      .map((d) => `- **${d.name}** (\`${d.file}\`) — ${d.why}`)
      .join('\n')
    return `### ${entry.subject}\n\n\`${entry.subjectFile}\`\n\n${deps}`
  }).join('\n\n')

  return `# Repos-Touched Quick Lookup

> Generated by [Legibly](https://github.com/prayasjain/legibly) on ${new Date().toISOString().slice(0, 10)}

When you change a module, other modules may break or need updating. This table shows the blast radius of each change.

## Quick reference

| If you change... | Also check... | Why |
|-----------------|---------------|-----|
${tableRows}

## Detail

${detailSections}

---

*Re-generate with \`legibly analyse --stitch-only\` after structural refactors.*
`
}
