import type { SystemAnalysis } from '../stitcher/types.js'

export function renderOnboarding(system: SystemAnalysis): string {
  const highRisk = system.services.filter((s) => s.riskLevel === 'high')
  const medRisk = system.services.filter((s) => s.riskLevel === 'medium')

  const serviceTable = system.services
    .map((s) => `| ${s.name} | ${s.riskLevel.toUpperCase()} | ${s.oneLiner} |`)
    .join('\n')

  const priorityList = system.onboardingPriority
    .map((p, i) => `${i + 1}. ${p}`)
    .join('\n')

  const criticalPathList = system.criticalPaths
    .map((p) => `### ${p.path}\n**Risk:** ${p.risk.toUpperCase()} — ${p.why}`)
    .join('\n\n')

  const systemFailureList = system.systemFailurePoints
    .map((f) => `- **[${f.severity.toUpperCase()}]** ${f.description}\n  *Affected:* ${f.affectedModules.join(', ')}`)
    .join('\n')

  const glossaryTable = system.domainGlossary
    .map((t) => `| \`${t.term}\` | ${t.meaning} |`)
    .join('\n')

  const assumptionList = system.systemAssumptions
    .map((a) => `- ${a}`)
    .join('\n')

  const riskList = system.biggestRisks
    .map((r, i) => `${i + 1}. ${r}`)
    .join('\n')

  const aliasSection = system.aliases
    .filter((a) => a.aliases.length > 0)
    .map((a) => `- **${a.canonical}** also appears as: ${a.aliases.map((x) => `\`${x}\``).join(', ')}`)
    .join('\n')

  return `# ${system.systemName} — Onboarding Guide

> Generated by [Legibly](https://github.com/prayasjain/legibly) on ${new Date().toISOString().slice(0, 10)}

## What this system does

${system.whatItDoes}

## Where to start — read in this order

${priorityList}

## Services at a glance

| Service | Risk | What it does |
|---------|------|-------------|
${serviceTable}

${highRisk.length > 0 ? `> **High-risk services (${highRisk.length}):** ${highRisk.map((s) => s.name).join(', ')} — read their service docs before touching anything.` : ''}
${medRisk.length > 0 ? `> **Medium-risk services (${medRisk.length}):** ${medRisk.map((s) => s.name).join(', ')}` : ''}

## Critical paths

${criticalPathList || '_No critical paths identified._'}

## System-level failure points

${systemFailureList || '_No system-level failure points identified._'}

## Domain glossary

| Term | Meaning |
|------|---------|
${glossaryTable || '_No domain terms identified._'}

## System-wide assumptions

These are things the whole system assumes but never validates:

${assumptionList || '_No system-wide assumptions identified._'}

## Biggest risks

${riskList || '_No risks identified._'}

${aliasSection ? `## Alias map\n\nThe same services appear under multiple names in this codebase:\n\n${aliasSection}` : ''}

---

*For detailed per-service documentation, see \`/legibly/services/\`.*
*For operational runbooks, see \`/legibly/runbooks/\`.*
*For AI agent context, see \`/legibly/specs/\`.*
`
}
