import type { SystemAnalysis } from '../stitcher/types.js'

export function renderRelationshipMap(system: SystemAnalysis): string {
  const { nodes, edges } = system.dependencyGraph

  // Group nodes by layer
  const byLayer = new Map<string, typeof nodes>()
  for (const node of nodes) {
    const layer = node.layer || 'unknown'
    if (!byLayer.has(layer)) byLayer.set(layer, [])
    byLayer.get(layer)!.push(node)
  }

  const layerSection = [...byLayer.entries()]
    .map(([layer, layerNodes]) => {
      const header = `### ${layer.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())}`
      const list = layerNodes.map((n) => `- **${n.label}** (\`${n.id}\`)`).join('\n')
      return `${header}\n${list}`
    })
    .join('\n\n')

  const edgeRows = edges
    .map((e) => {
      const fromNode = nodes.find((n) => n.id === e.from)
      const toNode = nodes.find((n) => n.id === e.to)
      return `| ${fromNode?.label ?? e.from} | ${e.label} | ${toNode?.label ?? e.to} |`
    })
    .join('\n')

  const aliasRows = system.aliases
    .filter((a) => a.aliases.length > 0)
    .map((a) => `| ${a.canonical} | ${a.file} | ${a.aliases.join(', ')} | ${a.dependents} |`)
    .join('\n')

  const coreServices = system.aliases
    .filter((a) => a.classification === 'core')
    .map((a) => `- **${a.canonical}** (${a.dependents} dependents) — \`${a.file}\``)
    .join('\n')

  return `# ${system.systemName} — Service Relationship Map

> Generated by [Legibly](https://github.com/prayasjain/legibly) on ${new Date().toISOString().slice(0, 10)}

## System overview

${system.whatItDoes}

## Load-bearing services

These are the core services — the most depended-upon. Changes here have the highest blast radius.

${coreServices || '_No core services identified._'}

## Services by layer

${layerSection || '_No layer information available._'}

## Dependency relationships

| From | Relationship | To |
|------|-------------|-----|
${edgeRows || '_No relationships mapped._'}

## Alias table

Some services appear under multiple names in this codebase:

| Canonical Name | File | Aliases | Dependents |
|----------------|------|---------|------------|
${aliasRows || '_No aliases detected._'}

## Critical paths

${system.criticalPaths.map((p) =>
  `### ${p.path}\n**Risk:** ${p.risk.toUpperCase()} — ${p.why}`
).join('\n\n') || '_No critical paths identified._'}
`
}
