import type { SystemAnalysis, GraphNode, GraphEdge } from '../stitcher/types.js'

export interface ProxyChain {
  path: string[]           // node labels from source → sink
  length: number
  description: string      // "A → B → C"
}

/**
 * Find all unique paths of length ≥ 2 through the dependency graph.
 * A → B → C means: changing C ripples through B to affect A.
 * We cap path length at 5 to avoid combinatorial explosion.
 */
export function computeProxyChains(
  nodes: GraphNode[],
  edges: GraphEdge[],
  maxDepth = 5
): ProxyChain[] {
  const labelById = new Map(nodes.map((n) => [n.id, n.label]))

  // Build adjacency: from → [to, ...]
  const adj = new Map<string, string[]>()
  for (const e of edges) {
    if (!adj.has(e.from)) adj.set(e.from, [])
    adj.get(e.from)!.push(e.to)
  }

  const chains: ProxyChain[] = []
  const seen = new Set<string>()

  function dfs(path: string[]): void {
    const current = path[path.length - 1]
    if (path.length >= 2) {
      const key = path.join('>')
      if (!seen.has(key)) {
        seen.add(key)
        const labels = path.map((id) => labelById.get(id) ?? id)
        chains.push({
          path: labels,
          length: path.length,
          description: labels.join(' → '),
        })
      }
    }
    if (path.length >= maxDepth) return
    for (const next of (adj.get(current) ?? [])) {
      if (!path.includes(next)) {   // no cycles
        dfs([...path, next])
      }
    }
  }

  for (const node of nodes) {
    dfs([node.id])
  }

  // Keep chains of length ≥ 2, sorted by length desc then alpha
  return chains
    .filter((c) => c.length >= 2)
    .sort((a, b) => b.length - a.length || a.description.localeCompare(b.description))
}

export function renderRippleMap(system: SystemAnalysis): string {
  const chains = computeProxyChains(
    system.dependencyGraph.nodes,
    system.dependencyGraph.edges
  )

  if (chains.length === 0) {
    return `# Proxy Chain Map

> Generated by [Legibly](https://github.com/prayasjain/legibly) on ${new Date().toISOString().slice(0, 10)}

No multi-hop dependency chains detected in this codebase.
`
  }

  // Group by length for readability
  const byLength = new Map<number, ProxyChain[]>()
  for (const c of chains) {
    if (!byLength.has(c.length)) byLength.set(c.length, [])
    byLength.get(c.length)!.push(c)
  }

  const maxLength = Math.max(...byLength.keys())

  const sections = Array.from(byLength.entries())
    .sort(([a], [b]) => b - a)
    .map(([len, cs]) => {
      const heading = len === maxLength
        ? `## Longest chains (${len} hops) — highest blast radius`
        : `## ${len}-hop chains`
      const list = cs.slice(0, 20).map((c) => `- \`${c.description}\``).join('\n')
      const overflow = cs.length > 20 ? `\n_…and ${cs.length - 20} more_` : ''
      return `${heading}\n\n${list}${overflow}`
    })
    .join('\n\n')

  return `# Proxy Chain Map

> Generated by [Legibly](https://github.com/prayasjain/legibly) on ${new Date().toISOString().slice(0, 10)}

A proxy chain is a multi-hop dependency path: **A → B → C** means changing C can ripple through B to affect A. The longer the chain, the wider the blast radius.

**${chains.length} chains found** across ${system.dependencyGraph.nodes.length} services (up to 5 hops deep).

${sections}

---

*Re-generate with \`legibly analyse --stitch-only\`.*
`
}
